services:
  api:
    build: ./services/api
    container_name: groupproject_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      ANALYSE_URL: http://analyse-py:8000

  frontend:
    build: ./services/frontend
    container_name: groupproject_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  ingestion:
    build: ./services/ingestion
    container_name: groupproject_ingestion
    ports:
      - "8001:8001"
    restart: unless-stopped

  analyse-py:
    build: ./services/analyse-py
    container_name: groupproject_analyse-py
    ports:
    - "8010:8000"
    environment:
      API_URL: http://api:8000
      ANALYSE-R_URL: http://analyse-r:8000
    restart: unless-stopped
  
  analyse-r:
    build: ./services/analyse-r
    container_name: groupproject_analyse-r
    ports:
    - "8020:8000"
    environment:
      API_URL: http://api:8000
      MODERATION_URL: http://moderation:8000
    restart: unless-stopped

  moderation:
    build: ./services/moderation
    container_name: groupproject_moderation
    ports:
    - "8030:8000"
    environment:
      API_URL: http://api:8000
    restart: unless-stopped
