name: psb1-127

services:
  api:
    build: ./services/api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - neo4j
      - redis
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: shitstorm_db
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      ANALYSE_URL: http://analyse-py:8000
      ANALYSE_R_URL: http://analyse-r:8000
    restart: unless-stopped

  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped


  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    restart: unless-stopped
  

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  ingestion:
    build: ./services/ingestion
    ports:
      - "8001:8001"
    depends_on:
    - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017
      MONGO_DB_NAME: shitstorm_db
    restart: unless-stopped

  analyse-py:
    build: ./services/analyse-py
    ports:
      - "8010:8000"
    depends_on:
      - api
      - llm-service
    environment:
      API_URL: http://api:8000
      ANALYSE_R_URL: http://analyse-r:8000
      LLM_SERVICE_URL: http://llm-service:8011
    restart: unless-stopped

  llm-service:
    build: ./services/LLM_service
    ports:
      - "8011:8011"
    env_file:
      - .env
    restart: unless-stopped

  analyse-r:
    build: ./services/analyse-r
    ports:
      - "8020:8000"
    depends_on:
    - api
    environment:
      API_URL: http://api:8000
      MODERATION_URL: http://moderation:8000
      MODEL_DOWNLOAD_URL: ${MODEL_DOWNLOAD_URL:-}
    mem_limit: 3g
    volumes:
      - analyse_r_models:/app/models
    restart: unless-stopped

  moderation:
    build: ./services/moderation
    ports:
      - "8030:8000"
    environment:
      API_URL: http://api:8000
      LLMAPI_KEY: ${LLMAPI_KEY}
    restart: unless-stopped

volumes:
  mongodb_data: {}
  neo4j_data: {}
  analyse_r_models: {}
